### ISSUE TITLE
Code Errors

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/modularity-mindfulness#2]
@hellachella
I'm not sure how to fix these errors
![Screenshot 2020-09-27 185914](https://user-images.githubusercontent.com/55193211/94378024-f7d64600-00f3-11eb-87a4-7c278f2c7a36.jpg)
![Screenshot 2020-09-27 185946](https://user-images.githubusercontent.com/55193211/94378025-f7d64600-00f3-11eb-9e4a-b361ce474207.jpg)

**Comment by hellachella** [comment]
- You have put a ```<body.``` tag inside your ```<main>```. You can't do that, the body is always only ever the outside most container. 

- In your h1
```
    <h1>
      <i lang="ja">枯山水</i><span>Rock Gardens</span>
    </h1>
```
They are not entirely separate but separated by more specific interior tags (i and span) so that you can target them in your css. 

- Move your banner image into the  ```<main>```. 

- Put all of your figures inside of articles. 
```
<article>
  <figure>
    /*content inside of the figure*/
  </figure>
<article>
```

- The hierarchy of this should look like so (but with the content of course):

```
<body>
  
  <header> <!-- display flex -->
    <h1> <!-- treat this <h1> as a container, use display flex and flex direction -->
      <i><!--content in ja--></i><!-- content in en -->
    </h1>
    <nav>
      <ul> <!-- display flex -->
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </nav>
  </header>

  <main>
    <img src="" alt="">
    <div class="">
      <!-- Intro info etc -->
    </div>

    <section> <!-- display grid -->
      <article class="">
        <!-- content -->
      </article>

      <article class="">
        <!-- content -->
      </article>

      <article class="">
        <!-- content -->
      </article>
    </section>

  </main>

  <footer>
    <!-- content -->
  </footer>
</body>
```

**Comment by AlexanderTahtadjian** [comment]
thanks
