### ISSUE TITLE
Navigation at 608

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/modularity-mindfulness#4]
@MacKenzieRose
I put some code on my nav to make it match when it hits 608, but its on top of my banner pic, I've tried some code to fix its position, to match its placement at 608 but it doesn't seem to be working.

**Comment by MacKenzieRose** [comment]
So your code (in your media query) is what's putting your `nav` items on top of the image. For now, I would remove all of the code styling your `ul` in your media query (lines 152–155). Then, for your header styling (line 42) instead of `display: contents`, let's use `display: flex` which should let your navigation and h1 sit beside each other.

Let me know if that helps! Tag me again if you get stuck~

**Comment by AlexanderTahtadjian** [comment]
It kind of worked but they now look like this
![Screenshot 2020-09-28 162917](https://user-images.githubusercontent.com/55193211/94482813-df276800-01a7-11eb-9386-da611bfa0f07.jpg)
![Screenshot 2020-09-28 162950](https://user-images.githubusercontent.com/55193211/94482815-dfbffe80-01a7-11eb-9bf0-8ebe93deab1b.jpg)

**Comment by MacKenzieRose** [comment]
Glad it's working so far!

## For the smaller screenshots:
You'll want to use your flexbox tools to align things vertically and in the center of the page. There are a few ways to do this, but I would suggest using `flex-direction: column` for your logo component, and pairing that with center-justified content for your navigation elements.

## For the larger screenshots:
You're pretty close to what you need already. By default, flexbox is putting your elements in the row direction, but if they change because of the above code, you can fix that in your media query. Then, all you need is for your navigation elements to go to the right side of the screen (maybe by getting your header to put space between the `h1` and the `nav` 😉 ).

**Comment by AlexanderTahtadjian** [comment]
ok, ill give it a try

**Comment by AlexanderTahtadjian** [comment]
Its getting there, but now this has happened
![Screenshot 2020-09-28 172533](https://user-images.githubusercontent.com/55193211/94487952-c9b63c00-01af-11eb-98a8-ab684cee0e12.jpg)
![Screenshot 2020-09-28 172602](https://user-images.githubusercontent.com/55193211/94487953-c9b63c00-01af-11eb-9691-a779e584e03c.jpg)
